# Generated by Django 4.2.6 on 2023-12-13 11:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_card_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
