# Generated by Django 4.2.6 on 2023-12-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_card_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='color',
            new_name='name',
        ),
        migrations.AddField(
            model_name='card',
            name='price',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
