# Generated by Django 4.2.6 on 2023-12-16 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename_color_card_name_card_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='description',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
