# Generated by Django 4.2.6 on 2023-12-16 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_card_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='description',
        ),
    ]
