# Generated by Django 4.2.6 on 2023-12-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_card_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='owner',
            field=models.TextField(),
        ),
    ]
